#:kivy 1.11.1

<MainWidget>:
    orientation: 'vertical'
    canvas:
        Color:
            rgb: 0.5,0.5,0.5
        Rectangle:
            size: self.size

    BoxLayout:
        orientation: 'horizontal'
        size_hint: (1,0.1)
        spacing: 10
        Label:
            text: 'SUPERVISÓRIO ESTEIRA'
            size_hint_x: None
            width: 300
        BoxLayout:
            orientation: 'vertical'
            size_hint_x: None
            width: 400
            Label:
                text: 'Configurações'
            BoxLayout:
                orientation:'horizontal'
                Button:
                    text: 'MODBUS'
                    on_release: root._modbusPopup.open()
                Button:
                    text: 'Scan Time'
                    on_release: root._scanPopup.open()
        Image: 
            id: img_con
            size_hint_x: None
            width: 80
            source: 'imgs/desconectado.png'
            pos_hint: {'top':1, 'right':1}

    FloatLayout:
        canvas:
            Color:
                rgb: 1,1,1
            Rectangle:
                size: self.size
        Image:
            id: imgEsteira
            source: 'imgs/imagem_de_fundo_certa.png'

        Label:
            id: lb_med_vel
            size_hint: (None, None)
            size:  (medidor_vel.size[0]*0.15, medidor_vel.size[1])
            pos_hint: {'x':0.83, 'y':0.36}
            canvas:
                Color:
                    rgb: 0.85,0.85,0.85
                Rectangle:
                    size: self.width * 4.8, self.height * 0.2
                    pos: (self.pos[0]+12, self.pos[1]+21)

        Label:
            id: lb_med_tq
            size_hint: (None, None)
            size:  (medidor_tq.size[0]*0.15, medidor_tq.size[1])
            pos_hint: {'x':0.26, 'y':0.17}
            canvas:
                Color:
                    rgb: 0.85,0.85,0.85
                Rectangle:
                    size: self.width * 4.8, self.height * 0.2
                    pos: (self.pos[0]+12, self.pos[1]+21)

        Label:
            id: lb_med_carga
            size_hint: (None, None)
            size:  (medidor_carga.size[0]*0.15, medidor_carga.size[1])
            pos_hint: {'x':0.6, 'y':0.67}
            canvas:
                Color:
                    rgb: 0.85,0.85,0.85
                Rectangle:
                    size: self.width * 4.8, self.height * 0.2
                    pos: (self.pos[0]+12, self.pos[1]+21)

        Label:
            id: lb_med_rot
            size_hint: (None, None)
            size:  (medidor_rot.size[0]*0.15, medidor_rot.size[1])
            pos_hint: {'x':0.26, 'y':0.35}
            canvas:
                Color:
                    rgb: 0.85,0.85,0.85
                Rectangle:
                    size: self.width * 4.8, self.height * 0.2  # Aumenta largura e reduz altura
                    pos: (self.pos[0]+12, self.pos[1]+21)  # Ajusta posição para alinhar corretamente

        Image:
            id: medidor_vel
            source: 'imgs/medidor.png'
            size_hint: 0.1,0.1
            pos_hint: {'x':0.83, 'y':0.36}

        Image:
            id: medidor_tq
            source: 'imgs/medidor.png'
            size_hint: 0.10,0.10
            pos_hint: {'x':0.26, 'y':0.17}

        Image:
            id: medidor_carga
            source: 'imgs/medidor.png'
            size_hint: 0.10,0.10
            pos_hint: {'x':0.6, 'y':0.67}

        Image:
            id: medidor_rot
            source: 'imgs/medidor.png'
            size_hint: (0.10,0.10)
            pos_hint: {'x':0.26, 'y':0.35}

        Button:
            size_hint:(None, None)
            size: (1.2*62, 1.2*58)   
            background_normal: 'imgs/graph_icone.png'
            background_down: 'imgs/graph_icone.png'
            pos_hint: {'x':0.05, 'y': 0.05}
            on_release: root._graph.open()

        Button:
            size_hint:(None, None)
            size: (1.15*62, 1.15*58)    # a imagem tem 62x58 pixels
            background_normal: 'imgs/PID.png'
            background_down: 'imgs/PID.png'
            pos_hint:{'x':0.87, 'y': 0.0}
            on_release:root._pidPopup.open()

        BoxLayout:
            orientation: 'vertical'
            size_hint: (0.1,0.1)
            pos_hint: {'x':0.83, 'y':0.3}
            Label:
                text: 'Velocidade da Esteira'
                font_size: 15
                bold: True
                halign: 'center'
                color: 0,0,0,1
            Label:
                id: VelocidadeEsteira
                text: '-.- m/min'
                font_size: 15
                bold: True
                halign: 'center'
                color: 0,0,0,1

        BoxLayout:
            orientation: 'vertical'
            size_hint: (0.1,0.1)
            background_color: 0,0,0,1
            pos_hint: {'x':0.6, 'y':0.6}
            Label:
                text: 'Carga na Esteira'
                font_size: 15
                bold: True
                halign: 'center'
                color: 0,0,0,1
            Label:
                id: CargaEsteira
                text: '-.- Kgf/cm²'
                font_size: 15
                bold: True
                halign: 'center'
                color: 0,0,0,1

        BoxLayout:
            orientation: 'vertical'
            size_hint: (0.1,0.1)
            pos_hint: {'x':0.26, 'y':0.1}
            Label:
                text: 'Torque'
                font_size: 15
                bold: True
                halign: 'center'
                color: 0,0,0,1
            Label:
                id: torque
                text: '-.- N.m'
                font_size: 15
                bold: True
                halign: 'center'
                color: 0,0,0,1

        BoxLayout:
            orientation: 'vertical'
            size_hint: (0.1,0.1)
            background_color: 0,0,0,1
            pos_hint: {'x':0.26, 'y':0.28}
            Label:
                text: 'Frequência de rotação'
                font_size: 15
                bold: True
                halign: 'center'
                color: 0,0,0,1
            Label:
                id: FrequenciaRotacao
                text: '-.- RPM'
                font_size: 15
                bold: True
                halign: 'center'
                color: 0,0,0,1
        
        Button:
            size_hint:(None, None)
            size: (1.2*62, 1.2*58)    # a imagem tem 62x58 pixels
            background_normal: 'imgs/Bancodedados.png'
            background_down: 'imgs/Bancodedados.png'
            pos_hint: {'x':0.0, 'y': 0.85}
            on_release: root._hgraph.open()

        Button:
            size_hint:(None, None)
            size: (1.2*62, 1.2*58)    
            background_normal: 'imgs/Medicoes.png'
            background_down: 'imgs/Medicoes.png'
            pos_hint:{'x':0.76, 'y': 0.005}
            on_release:root._medicoesPopup.open()

        Button:
            id: btnComando
            text: 'Comando'
            pos_hint:{'x':0.05, 'y':0.2} 
            size_hint:(0.14,0.05)
            padding: 10,10
            on_release:root._comandoPopup.open()

        Button:
            id: btnTemperatura
            size: (1.2*62, 1.2*58)    # a imagem tem 62x58 pixels
            size_hint:(None, None)
            background_normal: 'imgs/termometro.png'
            background_down: 'imgs/termometro.png'
            pos_hint:{'x':0.65, 'y': 0.0}            
            on_release:root._TemperaturaPopup.open()