#:kivy 1.11.1

<ModbusPopup>:
    title: "Configurações MODBUS"
    size_hint_y: None
    size_hint_x: 0.4
    height: 200
    BoxLayout:
        id: layout
        orientation: 'vertical'
        GridLayout:
            cols: 2
            rows: 2
            Label:
                text: "IP"
                font_size: 14
            TextInput:
                id: txt_ip
                text: "127.0.0.1"
                font_size: 14
                halign: 'center'
                valign: 'middle'
            Label:
                text: "Porta"
                font_size: 14
            TextInput:
                id: txt_port
                text: "502"
                font_size: 14
                halign: 'center'
                valign: 'middle'
        BoxLayout:
            orientation:'horizontal'
            Button:
                size_hint_y: None
                height: 40
                text: "Conectar"
                on_release:
                    root.clearInfo() 
                    app.root.startDataRead(txt_ip.text, int(txt_port.text))
            Button:
                size_hint_y: None
                height: 40
                text: "Fechar"
                on_release:
                    root.dismiss()
                    root.clearInfo()

<ScanPopup>:
    title: "Configuração ScanTime"
    size_hint_y: None
    size_hint_x: 0.4
    height: 150
    BoxLayout:
        id: layout
        orientation: 'vertical'
        GridLayout:
            cols: 2
            rows: 1
            Label:
                text: "ScanTime [ms]"
                font_size: 14
            TextInput:
                id: txt_st
                font_size: 14
                halign: 'center'
                valign: 'middle'
        BoxLayout:
            orientation:'horizontal'
            Button:
                size_hint_y: None
                height: 40
                text: "Configurar"
                on_release: 
                    app.root._scan_time = int(txt_st.text)
            Button:
                size_hint_y: None
                height: 40
                text: "Fechar"
                on_release:
                    root.dismiss()

<DataGraphPopup>:
    title: "Gráfico em tempo real"
    BoxLayout:
        orientation: 'vertical'
        TimeSeriesGraph:
            id: graph
            xlabel: 'Horário'
            ylabel: 'Medida'
            background_color: 0.5,0.5,0.5,0.5
            x_ticks_minor: 1
            x_ticks_major: 5
            y_ticks_major: 50
            y_grid_label: True
            x_grid_label: True
            padding: 5
            x_grid: True
            y_grid: True
            xmin: 0
            ymin:0
            ymax: 500
        BoxLayout:
            orientation: 'horizontal'
            size_hint: (1,0.05)
            BoxLayout:
                orientation: 'horizontal'
                size_hint: (0.5,1)
                BoxLayout:
                    orientation: 'vertical'
                    size_hint: (0.3,1)
                    Button:
                        text: 'Seleção de grandeza'
                        on_release: app.root._selectData.open()
                Label:
                    text: "Número de pontos do gráfico"
                    size_hint: (0.3,1)
                LabeledCheckBoxDataGraph:
                    id: mp20
                    on_kv_post: 
                        self.ids.label.text = '20'
                        self.ids.checkbox.group = 'cb_group'
                        self.ids.checkbox.active = True
                LabeledCheckBoxDataGraph:
                    id: mp50
                    on_kv_post: 
                        self.ids.label.text = '50'
                        self.ids.checkbox.group = 'cb_group'
                LabeledCheckBoxDataGraph:
                    id: mp100
                    on_kv_post: 
                        self.ids.label.text = '100'
                        self.ids.checkbox.group = 'cb_group'
                Button:
                    text: "Fechar"
                    size_hint: (0.2,1)
                    on_release: root.dismiss()

<LabeledCheckBoxDataGraph>:
    orientation: 'horizontal'
    size_hint: (0.1,1)
    CheckBox:
        id: checkbox
        on_active: app.root._graph.ids.graph.setMaxPoints(int(label.text),0) if app.root is not None else None
    Label:
        id: label

<HistGraphPopup>:
    title: "Histórico de medições da planta"
    BoxLayout:
        orientation: 'vertical'
        TimeSeriesGraph:
            id: graph
            xlabel: 'Horário'
            ylabel: 'Medida'
            background_color: 0.5,0.5,0.5,0.5
            x_ticks_minor: 1
            x_ticks_major: 5
            y_ticks_major: 50
            y_grid_label: True
            x_grid_label: True
            padding: 5
            x_grid: True
            y_grid: True
            xmin: 0
            ymin:0
            ymax:500
        BoxLayout:
            orientation:'horizontal'
            GridLayout:
                cols: 9
                rows: 7
                id: sensores   
                size_hint: (3,1)
            CheckBox:
                id: checkbox
                on_active: app.root.getDataDB()
        BoxLayout:
            orientation: 'horizontal'
            size_hint: (1,0.15)
            Label:
                text: 'Timestamp inicial \r\n [size=12] (DD/MM/AAAA HH:MM:SS)[/size]'
                halign: 'center'
                markup: True
            TextInput:
                id: txt_init_time
                size_hint: (1,0.8)
                halign: 'center'
                valign: 'middle'
                multiline: False
            Label:
                text: 'Timestamp final \r\n [size=12] (DD/MM/AAAA HH:MM:SS)[/size]'
                halign: 'center'
                markup: True
            TextInput:
                id: txt_final_time
                size_hint: (1,0.8)
                halign: 'center'
                valign: 'middle'
                multiline: False
            Button:
                text: "Fechar"
                size_hint: (1,0.8)
                on_release: root.dismiss()

<LabeledCheckBoxHistGraph>:
    orientation: 'horizontal'
    size_hint: (0.05,1)
    CheckBox:
        id: checkbox
        on_active: app.root.getDataDB()
    Label:
        id: label
        font_size: 12 
        bold: True


<PidPopup>:
    title:"Configuração e dados do PID"
    size_hint_y: None
    size_hint_x: 0.8
    height: 600
    BoxLayout:
        orientation: "vertical"
        GridLayout:
            cols: 2
            rows: 5
            Label: 
                text: "PV"
                font_size: 14
            Label:
                id: CargaEsteira
                text: '-.- Kgf/cm²'
                font_size: 14
                haligh: "center"
                valign: "middle"
            
            Label:
                text: 'Status do PID'
                font_size: 14
            Label:
                id: statusPID
                text: 'Desligado'
                font_size: 14
                haligh: "center"
                valign: "middle"
        BoxLayout:
            orientation: "vertical"
            Label:
                text: "Modo de operação:"
                font_size: 14
            GridLayout:
                cols: 2
                rows:2
                CheckBox:
                    id: AutomaticoOn
                    text: "Automático"
                    size: 50, 10
                    group: "Aut/Man"
                    active: False
                Label:
                    text:"Automático"
                CheckBox:
                    id: ManualOn
                    text: "Manual"
                    size: 50, 10
                    group: "Aut/Man"
                    
                    active: True
                Label:
                    text:"Manual"
        GridLayout:
            cols: 2
            rows:5
            Label:
                text: "Defina o Setpoint(SP):"
                font_size: 14
            TextInput:
                id: SetPoint
                font_size: 14
                text: ' '
                haligh: "center"
                valign: "middle"
                padding: 8,8,8,8
                on_text_validate: root.setSetPoint()
                multiline: False
            Label:
                text: "MV (%):"
                font_size: 14
            TextInput:
                id: VarManip
                text: ' '
                font_size: 14
                haligh: "center"
                valign: "middle"
                padding: [8, 8]
                on_text_validate: root.setMV()
                multiline: False
            Label:
                text: "P:"
                font_size: 14
            TextInput:
                id: ControleP
                font_size: 14
                text: "8.0"
                haligh: "center"
                valign: "middle"
                padding: [8, 8]
                on_text_validate: root.setP()   
                multiline: False
            Label:
                text: "I:"
                font_size: 14
            TextInput: 
                id: ControleI
                font_size: 14
                text: "5.0"
                haligh: "center"
                valign: "middle"
                padding: [8, 8]
                on_text_validate: root.setI()
                multiline: False
            Label:
                text: "D:"
                font_size: 14
            TextInput:
                id: ControleD
                font_size: 14
                text: "2.0"
                haligh: "center"
                valign: "middle"
                padding: [8, 8]
                on_text_validate: root.setD()
                multiline: False

<MedicoesPopup>:
    title:"Medições de variáveis elétricas"
    size_hint_y: None
    size_hint_x: 0.8
    height: 500
    BoxLayout:
        orientation: "vertical"
        GridLayout:
            cols: 6
            rows: 9
            Label:
                text: "Corrente Média"
                font_size: 14
            Label:
                id: CorrenteMedia
                text: '-.-'
                font_size: 14
                haligh: "center"
                valign: "middle"
            Label:
                text: "A"
                font_size: 14
            Label:
                text: "Tensão entre a fase R e S"
                font_size: 14
            Label:
                id: dppRS
                text: '-.-'
                font_size: 14
                haligh: "center"
                valign: "middle"
            Label:
                text: "V"
                font_size: 14
            Label:
                text: "Tensão entre a fase S e T"
                font_size: 14
            Label:
                id: dppST
                text: '-.-'
                font_size: 14
                haligh: "center"
                valign: "middle"
            Label:
                text: "V"
                font_size: 14
            Label:
                text: "Tensão entre a fase T e R"
                font_size: 14
            Label:
                id: dppTR
                text: '-.-'
                font_size: 14
                haligh: "center"
                valign: "middle"
            Label:
                text: "V"
                font_size: 14
            Label:
                text: "Frequência da rede"
                font_size: 14
            Label:
                id: FrequenciaRede
                text: '-.-'
                font_size: 14
                haligh: "center"
                valign: "middle"
            Label:
                text: "Hz"
                font_size: 14
            Label:
                text: "Corrente Fase R"
                font_size: 14
            Label:
                id: CorrenteR
                text: '-.-'
                font_size: 14
                haligh: "center"
                valign: "middle"
            Label:
                text: "A"
                font_size: 14
            Label:
                text: "Corrente Fase S"
                font_size: 14
            Label:
                id: CorrenteS
                text: '-.-'
                font_size: 14
                haligh: "center"
                valign: "middle"
            Label:
                text: "A"
                font_size: 14
            Label:
                text: "Corrente Fase T"
                font_size: 14
            Label:
                id: CorrenteT
                text: '-.-'
                font_size: 14
                haligh: "center"
                valign: "middle"
            Label:
                text: "A"
                font_size: 14
            Label:
                text: "Potência Ativa Total"
                font_size: 14
            Label:
                id: PotAtivaTotal
                text: '-.-'
                font_size: 14
                haligh: "center"
                valign: "middle"
            Label:
                text: "W"
                font_size: 14
            Label:
                text: "Potência Aparente Total"
                font_size: 14
            Label:
                id: PotAparenteTotal
                text: '-.-'
                font_size: 14
                haligh: "center"
                valign: "middle"
            Label:
                text: "W"
                font_size: 14
            Label:
                text: "Potência Reativa Total"
                font_size: 14
            Label:
                id: PotReativaTotal
                text: '-.-'
                font_size: 14
                haligh: "center"
                valign: "middle"
            Label:
                text: "W"
                font_size: 14
            Label:
                text: "Tipo de motor"
                font_size: 14
            Label:
                id: TipoMotor
                text: '-.-'
                font_size: 14
                haligh: "center"
                valign: "middle"
            Label:
                text: " "
                font_size: 14
            Label:
                text: "THD da Corrente da fase R"
                font_size: 14
            Label:
                id: THDCorrenteR
                text: '-.-'
                font_size: 14
                haligh: "center"
                valign: "middle"
            Label:
                text: "%"
                font_size: 14
            Label:
                text: "THD da Corrente da fase S"
                font_size: 14
            Label:
                id: THDCorrenteS
                text: '-.-'
                font_size: 14
                haligh: "center"
                valign: "middle"
            Label:
                text: "%"
                font_size: 14
            Label:
                text: "THD da Corrente da fase T"
                font_size: 14
            Label:
                id: THDCorrenteS
                text: '-.-'
                font_size: 14
                haligh: "center"
                valign: "middle"
            Label:
                text: "%"
                font_size: 14

<TemperaturaPopup>:
    title:"Medidas de temperatura"
    size_hint_y: None
    size_hint_x: 0.8
    height: 250
    BoxLayout:
        orientation: "vertical"
        GridLayout:
            cols: 3
            rows: 4
            Label:
                text: "Temperatura na carcaça do motor"
                font_size: 14
            Label:
                id: TempCarc
                text: '-.-'
                font_size: 14
                haligh: "center"
                valign: "middle"
            Label:
                text: "ºC"
                font_size: 14
            Label:
                text: "Temperatura no enrolamento R"
                font_size: 14
            Label:
                id: tempR
                text: '-.-'
                font_size: 14
                haligh: "center"
                valign: "middle"
            Label:
                text: "ºC"
                font_size: 14
            Label:
                text: "Temperatura no enrolamento S"
                font_size: 14
            Label:
                id: tempS
                text: '-.-'
                font_size: 14
                haligh: "center"
                valign: "middle"
            Label:
                text: "ºC"
                font_size: 14
            Label:
                text: "Temperatura no enrolamento T"
                font_size: 14
            Label:
                id: tempT
                text: '-.-'
                font_size: 14
                haligh: "center"
                valign: "middle"
            Label:
                text: "ºC"
                font_size: 14

<ComandoPopup>:
    title:"Comandos do motor"
    separator_color: 0, 0, 0, 1
    size_hint_y: None
    size_hint_x: 0.95
    height: 350
    GridLayout:
        cols:3
        spacing: 10
        canvas.before:
            Color:
                rgba: 0.9, 0.9, 0.9, 1
            Rectangle:
                pos: self.pos
                size: self.size
        BoxLayout:
            orientation: "vertical"
            size_hint_x: 0.3
        
            spacing:10
            canvas.before:
                Color:
                    rgba: 0.8, 0.8, 0.8, 1
                Rectangle:
                    pos: self.pos
                    size: self.size
            Label:
                text: "Comandos na esteira"
                font_size: 14
                color: 0, 0, 0, 1  # Cor preta

            Button:
                background_color: 0.5, 0.5, 0.5, 0.5
                background_normal: ''
               
                text: "Ligar"
                padding: [8, 8]
                height: 100
                on_release: root.setOperacao(1)
              
            Button:
                background_color: 0.5, 0.5, 0.5, 0.5
                background_normal: ''
               
                text: "Desligar"
                
                padding: [8, 8]
                height: 100
                on_release: root.setOperacao(0)
 
            Button:
                background_color: 0.5, 0.5, 0.5, 0.5
                background_normal: ''
                text: "Reset"
                padding: [8, 8]
                height: 100
                on_release: root.setOperacao(2)
           
        BoxLayout:
            orientation: "vertical"
            spacing:10
            size_hint_x: 0.3
            size_hint_y: 0.98
            canvas.before:
                Color:
                    rgba: 0.8, 0.8, 0.8, 1
                Rectangle:
                    pos: self.pos
                    size: self.size
            Label: 
                text: "Tipo de partida"
                font_size: 14
                color: 0, 0, 0, 1  # Cor preta
            Button:
                background_color: 0.5, 0.5, 0.5, 1  # Cinza
        
                text: "Partida Direta"
                height: 100
                on_release: root.setPartida('Direta')
      
            Button:
                background_color: 0.5, 0.5, 0.5, 1  # Cinza
                text: "Partida pelo Inversor"
                height: 100
                on_release: root.setPartida('Inversor')
         
            Button:
                background_color: 0.5, 0.5, 0.5, 1  # Cinza
                text: "Partida Soft-Start"
                height: 100
                on_release: root.setPartida('Soft-Start')
        BoxLayout:
            orientation: "vertical"
            spacing:10
            size_hint_x: 0.3
            size_hint_y: 0.98
            canvas.before:
                Color:
                    rgba: 0.8, 0.8, 0.8, 1
                Rectangle:
                    pos: self.pos
                    size: self.size

            BoxLayout:
                orientation: "horizontal"
                size_hint_X:0.75
                BoxLayout:
                    orientation: "vertical"
                    Label:
                        text:"Inversor"
                        color: 0, 0, 0, 1  # Cor preta

                    GridLayout:
                        cols:2
                        rows:2
                        Label:
                            text: "Acel.(s)"
                            color: 0, 0, 0, 1  # Cor preta

                        TextInput:
                            id: RampaAcelInv
                            font_size: 14
                            text: "10"
                            haligh: "center"
                            valign: "middle"
                            padding: [8, 8]
                            on_text_validate: root.setAcc()
                            multiline: False
                            background_color: 0.9, 0.9, 0.9, 1  # Cor cinza claro
                            foreground_color: 0, 0, 0, 1  # Texto preto

                        Label:
                            text: "Desacel.(s)"
                            color: 0, 0, 0, 1  # Cor preta

                        TextInput:
                            id: RampaDesacelInv
                            font_size: 14
                            text: "10"
                            haligh: "center"
                            valign: "middle"
                            padding: [8, 8]
                            background_color: 0.9, 0.9, 0.9, 1  # Cor cinza claro
                            foreground_color: 0, 0, 0, 1  # Texto preto
                            on_text_validate: root.setDcc()
                            multiline: False
                    BoxLayout:
                        orientation: "vertical"
                        Label:
                            haligh: "center"
                            text:"      Min: 10s Max: 60s"
                            color: 0, 0, 0, 1  # Cor preta

                    BoxLayout:
                        orientation: "vertical"
                        Label:
                            text:"Velocidade(0 a 60Hz)"
                            color: 0, 0, 0, 1  # Cor preta
                            bold: True
                        TextInput:
                            id: VelInv
                            font_size: 14
                            text: "60"
                            haligh: "center"
                            valign: "middle"
                            padding: [8, 8]
                            on_text_validate: root.setVelInversor()
                            background_color: 0.9, 0.9, 0.9, 1  # Cor cinza claro
                            foreground_color: 0, 0, 0, 1  # Texto preto
                            multiline: False

<SelectDataGraphPopup>:
    title: "Seleção de grandeza"
    size_hint: (0.8,1)
    BoxLayout:
        orientation: 'vertical'
        GridLayout:
            cols: 4
            rows: 11
            id: sensores
            CheckBox:
                id:checkVelocidadeEsteira
                group: 'select_group'
                on_active: app.root._selected_grandeza='VelocidadeEsteira' if app.root is not None else None
            Label:
                text: "Velocidade da Esteira (m/min)"
            CheckBox:
                id:checktorque
                group: 'select_group'
                on_active: app.root._selected_grandeza='torque' if app.root is not None else None
            Label:
                text: "Torque (N.m)"
            CheckBox:
                id:checkFrequenciaRotacao
                group: 'select_group'
                on_active: app.root._selected_grandeza='FrequenciaRotacao' if app.root is not None else None
            Label:
                text: "Frequencia de Rotação (RPM)"
            CheckBox:
                id:checkCargaEsteira
                group: 'select_group'
                on_active: app.root._selected_grandeza='CargaEsteira' if app.root is not None else None
            Label:
                text: "Carga (Kgf/cm²)"
            CheckBox:
                id:checkTempCarc
                group: 'select_group'
                on_active: app.root._selected_grandeza='TempCarc' if app.root is not None else None
            Label:
                text: "Temperatura da Carcaça (ºC)"
            CheckBox:
                id:checkCorrenteMedia
                group: 'select_group'
                on_active: app.root._selected_grandeza='CorrenteMedia' if app.root is not None else None
            Label:
                text: "Corrente Média (A)"
            CheckBox:
                id:checkPotAtivaTotal
                group: 'select_group'
                on_active: app.root._selected_grandeza='PotAtivaTotal' if app.root is not None else None
            Label:
                text: "Potência Ativa (W)"
            CheckBox:
                id:checkPotReativaTotal
                group: 'select_group'
                on_active: app.root._selected_grandeza='PotReativaTotal' if app.root is not None else None
            Label:
                text: "Potência Reativa (W)"
            CheckBox:
                id:checkPotAparenteTotal
                group: 'select_group'
                on_active: app.root._selected_grandeza='PotAparenteTotal' if app.root is not None else None
            Label:
                text: "Potência Aparente (W)"
            CheckBox:
                id:checkFrequenciaRede
                group: 'select_group'
                on_active: app.root._selected_grandeza='FrequenciaRede' if app.root is not None else None
            Label:
                text: "Frequência Rede (Hz)"
            CheckBox:
                id:checkdppRS
                group: 'select_group'
                on_active: app.root._selected_grandeza='dppRS' if app.root is not None else None
            Label:
                text: "Tensão RS (V)"
            CheckBox:
                id:checkdppST
                group: 'select_group'
                on_active: app.root._selected_grandeza='dppST' if app.root is not None else None
            Label:
                text: "Tensão ST (V)"
            CheckBox:
                id:checkdppTR
                group: 'select_group'
                on_active: app.root._selected_grandeza='dppTR' if app.root is not None else None
            Label:
                text: "Tensão TR (V)"
            CheckBox:
                id:checkCorrenteR
                group: 'select_group'
                on_active: app.root._selected_grandeza='CorrenteR' if app.root is not None else None
            Label:
                text: "Corrente R (A)"
            CheckBox:
                id:checkCorrenteS
                group: 'select_group'
                on_active: app.root._selected_grandeza='CorrenteS' if app.root is not None else None
            Label:
                text: "Corrente S (A)"
            CheckBox:
                id:checkCorrenteT
                group: 'select_group'
                on_active: app.root._selected_grandeza='CorrenteT' if app.root is not None else None
            Label:
                text: "Corrente T (A)"
            CheckBox:
                id:checktempR
                group: 'select_group'
                on_active: app.root._selected_grandeza='tempR' if app.root is not None else None
            Label:
                text: "Temperatura R (ºC)"
            CheckBox:
                id:checktempS
                group: 'select_group'
                on_active: app.root._selected_grandeza='tempS' if app.root is not None else None
            Label:
                text: "Temperatura S (ºC)"
            CheckBox:
                id:checktempT
                group: 'select_group'
                on_active: app.root._selected_grandeza='tempT' if app.root is not None else None
            Label:
                text: "Temperatura T (ºC)"
            CheckBox:
                id:checkTHDCorrenteR
                group: 'select_group'
                on_active: app.root._selected_grandeza='THDCorrenteR' if app.root is not None else None
            Label:
                text: "THD Corrente R"
            CheckBox:
                id:checkTHDCorrenteS
                group: 'select_group'
                on_active: app.root._selected_grandeza='THDCorrenteS' if app.root is not None else None
            Label:
                text: "THD Corrente S"
            CheckBox:
                id:checkTHDCorrenteT
                group: 'select_group'
                on_active: app.root._selected_grandeza='THDCorrenteT' if app.root is not None else None
            Label:
                text: "THD Corrente T"